# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['hp-server-cadvisor-exporter:8080']

  - job_name: 'speedtest'
    static_configs:
      - targets: ['hp-server-speedtest-exporter:9798']
    scrape_interval: 60m
    scrape_timeout: 30s

  - job_name: 'hp-server-node-exporter'
    static_configs:
      - targets: ['hp-server-node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'piaus-node-exporter'
    static_configs:
      - targets: ['172.168.1.9:9100']
    scrape_interval: 30s
  